name: Update version in TOML files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  modify_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version in TOML files
        run: |
          # Extract the current version from the TOML file
          CURRENT_VERSION=$(awk -F '"' '/^version/ {print $2}' llama-cpp-2/Cargo.toml)
          # Increment the version
          NEXT_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{++$NF; print}')
          # Update version in llama-cpp-sys-2 Cargo.toml
          sed -i "s/^version = \".*\"/version = \"$NEXT_VERSION\"/g" llama-cpp-sys-2/Cargo.toml
          # Update version in llama-cpp-2 Cargo.toml
          sed -i "s/^version = \".*\"/version = \"$NEXT_VERSION\"/g" llama-cpp-2/Cargo.toml
          sed -i "s/^\(llama-cpp-sys-2 = { path = \"\.\.\/llama-cpp-sys-2\", version = \)\"$CURRENT_VERSION\"/\1\"$NEXT_VERSION\"/" llama-cpp-2/Cargo.toml
          # Commit the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add llama-cpp-sys-2/Cargo.toml llama-cpp-2/Cargo.toml
          git commit -m "Bump version to $NEXT_VERSION [skip ci]"
          # Push the changes back to the repository
          git push origin main:$GITHUB_REF
